### ISSUE TITLE
Zero loss for LOZO, and missing run.py 

### ISSUE THREAD

**Issue by JackyXiao98** [optsuite/LOZO#2]
Dear author,

Thank you for the open source code, it's very helpful! I had some issues when running the code, and kindly ask for help.

When I run opt-1.3b on SST2, the loss is always zero and the final accuracy is 0.5, which is strange. I'm using the default lozo.sh and change TASK=SST2. I tried MEZO and it runs normally, the loss decreases and the accuracy is around 0.8. Could you let me know if I need to tune other parameters?

Another thing is that, I have the following error when running the ICL code,

python: can't open file '/root/LOZO/large_models/run.py': [Errno 2] No such file or directory

It looks like run.py is missing.

**Comment by itongggg** [comment]
> Dear author,
> 
> Thank you for the open source code, it's very helpful! I had some issues when running the code, and kindly ask for help.
> 
> When I run opt-1.3b on SST2, the loss is always zero and the final accuracy is 0.5, which is strange. I'm using the default lozo.sh and change TASK=SST2. I tried MEZO and it runs normally, the loss decreases and the accuracy is around 0.8. Could you let me know if I need to tune other parameters?
> 
> Another thing is that, I have the following error when running the ICL code,
> 
> python: can't open file '/root/LOZO/large_models/run.py': [Errno 2] No such file or directory
> 
> It looks like run.py is missing.


Thank you for your appreciation. 
Our main programs are `run_mezo.py` and `run_lozo.py`. If you have any questions or suggestions, please feel free to let us know. We greatly appreciate your feedback and look forward to any further contributions.

**Comment by JackyXiao98** [comment]
Hi thank you for replying, the issue is that when running run_lozo.py, the loss is always 0, and the prediction score are NAN, could you let me know if the default parameters need to be changed?

<img width="1540" alt="image" src="https://github.com/user-attachments/assets/02a0b622-7812-4034-b2ed-bbd19b034071">

**Comment by itongggg** [comment]
can you provide your detailed parameters setting

**Comment by itongggg** [comment]
We have identified and fixed the bugs:

- In `run_lozo.py`, the `trainer` parameter should be set as "LOZO".
- However, in `LOZOtrainer.py`, it requires the `trainer` parameter to be set as "lowrank_zo".

We have resolved this issue by ensuring that both files now consistently use the "LOZO" parameter.

Thank you for bringing this to our attention!

**Comment by JackyXiao98** [comment]
Great, the issue is resolved. Thank you!

**Comment by itongggg** [comment]
@JackyXiao98 
Thank you for your feedback
